name = "supabase-auth-helpers-sveltekit"
account_id = "my-cloudflare-account-id"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "npm run build"

compatibility_date = "2022-07-07"
workers_dev = true

[vars]
VITE_SUPABASE_URL = "https://my-supabase-url.supabase.co"
VITE_SUPABASE_ANON_KEY = "my-supabase-jwt"
